import Head from 'next/head'


import App from '@/components/App'




export default function Home() {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/weather.png" />
      </Head>
      <main>
        <div>
        <App/>
        </div>
      </main>
    </>
  )
}
